version: '2'

services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-admin
    ports:
      - "6767:8080"
    volumes:
      - ./applogs:/data/applogs
    ports:
      - 8001:8080
    environment:
      TZ: Asia/Shanghai
      PARAMS: '--spring.datasource.url=jdbc:mysql://192.168.1.2:23306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password='
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

#  xxl-job-db:
#      image: mysql:5.7
#      container_name: xxl-job-db
#      environment:
#        TZ: Asia/Shanghai
#        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#      depends_on:
#        - xxl-job-dbdata
#      ports:
#        - "23306:3306"
#      volumes:
#        - ./sql:/docker-entrypoint-initdb.d
#      volumes_from:
#        - xxl-job-dbdata
#
#  xxl-job-dbdata:
#      image: alpine:latest
#      container_name: xxl-job-dbdata
#      volumes:
#        - /var/lib/mysql
